theme: minima
title: Blog (Araling Panlipunan)
author: Rein L.
description: Paglalahad ng mga malikhaing paraan at hakbang na maaaring isagawa ng mga kabataang tulad mo upang maipakita ang iyong suporta at maiwasan ang paglaganap ng diskriminasyon. Napili ko na gawin ito sa pamamagitan ng 「ｂｌ０ｇ」。
